name: Nix

on:
  push:
    branches: [master]

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  cache:
    name: Cache derivation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v14
        with:
          name: cofob
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build derivations
        run: |
          nix build .#aeza-assistant
